Use "safe_save_to" method to check the seekability when download files
reef-technologies/B2_Command_Line_Tool pull request #211
Opened 2023-10-17 09:00 UTC by athakur-reef

2023-10-17 09:56 UTC, mjurbanski-reef commented
what about
``
* support `-` as /dev/stdout alias in CLI IF no file with such name exists in current directory (same way we do it for - input)
```?

2023-10-17 12:57 UTC, athakur-reef commented
Support `-` as `/dev/stdout` alias.
- Used `CON` for stdout at Windows like `/dev/stdout` at Linux

2023-10-17 15:11 UTC, mjurbanski-reef commented on b2/console_tool.py
> +        if os.path.exists('-'):
please warn user about deprecation of this like we do on stdin alias

2023-10-17 15:35 UTC, athakur-reef commented
- Warn user about deprecation of this like we do on stdin alias

2023-10-17 16:34 UTC, athakur-reef commented
- Used updated `save_to` method for download

2023-10-17 17:23 UTC, mjurbanski-reef requested changes
see https://github.com/reef-technologies/b2-sdk-python/pull/309/files/4916ab1f1cd818711e7b44cd685a86995b0eae47#diff-41b295fa3878a7f108434f848eadaf27760e8dc8b4a4bde9cf4750ca57b91583

otherwise PR for CLI seems good :)

2023-10-17 17:23 UTC, mjurbanski-reef commented on CHANGELOG.md
> +* Fix to support '-' as stdout alias
this is new feature and not a fix

2023-10-17 19:09 UTC, athakur-reef commented
- Change the CLI to provide stdout without changing the SDK

2023-10-17 21:39 UTC, ppolewicz reviewed
I think both PRs missed an important thing: why and when we use wb+ vs wb. That's messed up and was messed up for years now for no good reason. We have a chance to fix it now but it doesn't seem that we are taking it.

2023-10-17 21:39 UTC, ppolewicz commented on CHANGELOG.md
> +
this line should not be there

2023-10-17 21:39 UTC, ppolewicz commented on CHANGELOG.md
> +
this too

2023-10-17 21:39 UTC, ppolewicz commented on b2/console_tool.py
> +    def get_download_info_from_local_filename(self, filename: str):
```suggestion
    def _get_download_info_from_local_filename(self, filename: str):
```
the convention in this file is to prefix protected method names with a `_`

2023-10-17 21:39 UTC, ppolewicz commented on b2/console_tool.py
> +        stdout_file_path = 'CON' if platform.system() == 'Windows' else '/dev/stdout'
that should be a (class) const so that it's computed once per program execution and not on every single download call. Here it doesn't matter much because CLI use is one-shot, but generally in terms of how you arrange the code, this should be a constant

2023-10-17 21:39 UTC, ppolewicz commented on b2/console_tool.py
> +        mode = 'wb+' if allow_seeking else 'wb'
I think we should be using the same thing for named pipes and it should generally be not CLI but sdk

2023-10-19 02:43 UTC, ppolewicz commented on CHANGELOG.md
> +* Fix failing open non-seekable file
there is something wrong grammaticaly with this line

2023-10-19 02:43 UTC, ppolewicz commented on CHANGELOG.md
> +* Support of `-` as a valid filename in `download-file-by-name` or `download-file-by-id` command. In future `-` will be an alias for standard output.
I think people typically write "in THE future", right?

2023-10-19 02:43 UTC, ppolewicz commented on b2/console_tool.py
> +        return filename
```suggestion
        if filename != '-':
            return filename
        if not os.path.exists(filename):
            return self.STDOUT_FILE_PATH
        self._print_stderr(
            "WARNING: Filename `-` won't be supported in the future and will be treated as stdout alias."
        )
        return filename
```

2023-10-19 02:43 UTC, ppolewicz commented on b2/console_tool.py
> +    def _correct_local_filename(self, filename: str):
This method does not correct a local filename, so its name is confusing. It should be renamed in such a way that the reader can figure out what it does without reading the code to understand what it does.

2023-10-19 02:43 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +        stdout_fd = os.dup(1)
should use something like `STDOUT_DESCRIPTOR = sys.stdout.fileno()` instead of a hardcoded `1` here

2023-10-19 02:43 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +    def test_download_to_non_seekable_file(self):
you have added new logic in `_correct_local_filename`, but you haven't added any unit tests for it, while the integration tests for this new feature are insufficient.

2023-11-20 20:51 UTC, closed without merging