ApiVer for command line
reef-technologies/B2_Command_Line_Tool pull request #238
Opened 2023-12-13 11:08 UTC by kkalinowski-reef

- `_b2v4`, `b2v3` and `b2` (pointing to `b2v3`) provided as binaries;
- tests running for both versions `3` and `4`;
- ability to specify version in both unit and integration tests;
- ability to force version for integration tests using particular `sut`.

2023-12-21 10:19 UTC, mjurbanski-reef requested changes
all new modules should be moved to `b2._internal` to discourage anyone from trying to import from them

2023-12-21 10:19 UTC, mjurbanski-reef commented on b2.spec.template
> +a = Analysis(['b2/${VERSION}/__main__.py'],
what happend with the plan to do it with https://pyinstaller.org/en/stable/spec-files.html#multipackaging-with-one-file-apps?

2023-12-21 10:40 UTC, kkalinowski-reef commented on b2.spec.template
> +a = Analysis(['b2/${VERSION}/__main__.py'],
You have to keep all the binaries in the same place with some generated files, thus breaking the requirement of them being self-contained.

2023-12-21 12:53 UTC, mjurbanski-reef approved these changes
This is great !

Please address the comment + make sure README explains to user difference between `b2` and `b2v3` - most importantly, the fact that for scripting they should use `b2v3`.

2023-12-21 12:53 UTC, mjurbanski-reef commented on noxfile.py
> +    # This may not hold true after version 10.
adding `key=lambda x: [int(num) for num in re.findall(r'\d+', x)]` in  get_versions should fix this

2023-12-21 12:53 UTC, mjurbanski-reef commented on changelog.d/+apiver_for_cli.infrastructure.md
> +Client binary is now handled with ApiVer methodology in mind. `b2` executable points to the latest stable version, while other versions can be called directly.
since you also moved internal stuff  (also the old ones) to `_internal` please also add `changed` note in addition to this

2023-12-22 05:09 UTC, kkalinowski-reef commented on noxfile.py
> +    # This may not hold true after version 10.
I went with a slightly different solution, that matches the behaviour of the `b2/_internalg/version_listing.py:get_versions()`.

2023-12-22 10:57 UTC, closed without merging