migrate cli flags to kebab case
reef-technologies/B2_Command_Line_Tool pull request #257
Opened 2024-03-01 23:51 UTC by andreea-popescu-reef

2024-03-04 21:50 UTC, vbaltrusaitis-reef requested changes
As discussed internally, we'd like to completely remove all `--camelCase` references in code. `--camelCase` should be supported only via an automatic translation layer for `b2v3`, not because some parameters still use that variant in `console_tool.py`.

2024-03-04 21:50 UTC, vbaltrusaitis-reef commented on b2/_internal/arg_parser.py
> +def add_normalized_argument(parser, param_name, *args, **kwargs):
As discussed internally, we'd like to fully migrate to kebab variants in the codebase, and support camel variants by translation / these additions in b2v3. This means that
1. This function should expect only kebab case (e.g. no need to do `dist` rewriting, just pass `param_name` directly to `add_argument`).
2. Every camel type arg should be rewritten in kebab style in `add_normalized_argument` calls.
3. `arg.camelCase` should be fixed accordingly where applicable.

There's probably more changes needed, but you get the point.

2024-03-04 21:50 UTC, vbaltrusaitis-reef commented on b2/_internal/arg_parser.py
> +    )
Constructing this type like this here and then matching on the name in autocomplete_cache seems a bit too implicit, there's nothing connecting these two. Could you extract the logic of constructing the type and checking if it matches in a common module (somewhere where it makes sense)? I'd also suggest that some `DeprecatedMixin` might be better for checking if the action is deprecated, rather than just the name of the class.

2024-03-05 23:41 UTC, vbaltrusaitis-reef approved these changes
A couple of minor nitpicks and a question.

2024-03-05 23:41 UTC, vbaltrusaitis-reef commented on changelog.d/+kebab.changed.md
> +Added deprecation warning for b2v3 --camelCase cli flags.
The changelog seems to be mostly using imperative forms, e.g. "add", "migrate", etc.

2024-03-05 23:41 UTC, vbaltrusaitis-reef commented on b2/_internal/arg_parser.py
> +    )
A question: any particular reason to use this somewhat obscure `type` invocation here instead of creating a `class _DeprecatedAction(action, DeprecatedActionMarker):` and assigning that to `kwargs_camel['action']`? I might be genuinely missing something here.

2024-03-05 23:41 UTC, vbaltrusaitis-reef commented on b2/_internal/arg_parser.py
> +                file=sys.stderr
I think `WARNING: ` before the message would be in order.

2024-03-06 05:20 UTC, andreea-popescu-reef commented on b2/_internal/arg_parser.py
> +    )
ah no, you're right - refactored

2024-03-28 13:25 UTC, mjurbanski-reef commented
merged upstream already

2024-03-28 13:25 UTC, closed without merging