Use `InMemoryAccountInfo` when using env vars for authentication
reef-technologies/B2_Command_Line_Tool pull request #263
Opened 2024-03-20 11:55 UTC by agoncharov-reef

**Current behavior:**
When users use env vars for authenticating in B2, those credentials are stored in `~/.b2_account_info` file which is unexpected by users and exposes B2 secrets to everyone who can read the file.

**New behavior:**
If user uses env vars for authentication, console tool uses `InMemoryAccountInfo` for storing account info and `InMemoryCache` for caching data.

Exception: when user calls `authorize-account` or `clear-account` commands, they store (or clear) credentials *on disk* even if "env vars authorization" is used.

--

This PR also removes `b2_api` parameter from `ConsoleTool` class init method. It was used only in tests and allowed passing mocked `B2Api` instance, however it added complexity to production code in case when special parameters were passed (like `--max_download_streams_per_file`): those parameters should be passed to `B2Api` during initialization, but `ConsoleTool` received already initialized mocked `B2Api` instance and thus those parameters couldn't be applied.

This is fixed by delegating `B2Api` initialization to `ConsoleTool` entirely, and for tests we use monkeypatching which substitutes few functions used to initialize `B2Api` inside `ConsoleTool`.

2024-03-21 16:58 UTC, mjurbanski-reef commented on changelog.d/+not-saving-auth-data-when-env-vars.fixed.md
> +Fix persisting credentials on disk even if environment variables were used for authentication.
```suggestion
Don't persist credentials provided in the Enviornment variables in any command other than `authorize-account`.
```
this seems to better explain the new behavior since "Fix" doesn't quite indicate if its now going to be saved or not

2024-03-21 16:58 UTC, mjurbanski-reef commented on b2/_internal/console_tool.py
> +            self.api = _get_b2api_for_profile(profile=args.profile, **kwargs)
something that would be "cool" is

IF key id from env matches the ones from the profile
THEN use persisted profile
ELSE use inmemory

this will allow for those who are OK with persisting data on disk, but not ok with the performance penalty to do `b2 authorize-account` first and then still keep all the benefits of using cache

2024-03-21 16:58 UTC, mjurbanski-reef commented on test/unit/test_console_tool.py
> +        # returns already predefined instance
:+1: 

IMO the name is wrong in SDK, i.e. it should have always been called "factory" to facility exactly this kind of shenanigans

2024-03-21 18:31 UTC, mjurbanski-reef requested changes
please make the change only affect b2v4 and not b2v3 since we don't want it to be "breaking"

2024-03-25 11:23 UTC, agoncharov-reef commented on b2/_internal/console_tool.py
> +            self.api = _get_b2api_for_profile(profile=args.profile, **kwargs)
Ah you caught me! I had exactly same thoughts BUT it was not that easy cause we authorize much later than instantiating b2 api. I will try to do something clever here

2024-03-26 15:32 UTC, mjurbanski-reef commented on b2/_internal/console_tool.py
> +        b2_api = _get_b2api_for_profile(profile=args.profile, **kwargs)
if I understand correctly, most of the work required not to create this is to expose `b2sdk.account_info.sqlite_account_info.SqliteAccountInfo._get_user_account_info_path` in public interface i.e.
remove `_` prefix in `_get_user_account_info_path`

seems like relatively small change and we would not have to have this big comment here :D

2024-03-26 15:33 UTC, mjurbanski-reef approved these changes
nice work!

2024-03-26 15:38 UTC, mjurbanski-reef commented on changelog.d/+not-saving-auth-data-when-env-vars.fixed.md
> +Don't persist credentials provided in the Enviornment variables in any command other than `authorize-account`.
```suggestion
Don't persist credentials provided in the Enviornment variables in any command other than `authorize-account` when using `b2v4`.
```

2024-03-27 10:26 UTC, closed without merging