Use short description from docstring as usage help
reef-technologies/B2_Command_Line_Tool pull request #290
Opened 2024-05-07 16:22 UTC by olzhasar-reef

2024-05-07 18:15 UTC, mjurbanski-reef requested changes
```
usages:
  b2 account   Account management subcommands.
  b2 bucket   Bucket management subcommands.
  b2 file   File management subcommands.
  b2 info   Prints all of the information about the object, but not its contents.
  b2 install-autocomplete   Installs autocomplete for supported shells.
  b2 key   Application keys management subcommands.
  b2 license   Prints the license of B2 Command line tool and all libraries shipped with it.
  b2 ls   Using the file naming convention that / separates folder names from their contents, returns
  b2 replication   Replication rule management subcommands.
  b2 rm   Removes a "folder" or a set of files matching a pattern. Use with caution.
  b2 sync   Copies multiple files from source to destination. Optionally deletes or hides destination
  b2 version   Prints the version number of this tool.
```

This looks almost good, but:
* its hard to determine where command ends and where description beings  - ideally all would be aligned as they are in git, i.e.
```
   bisect    Use binary search to find the commit that introduced a bug
   diff      Show changes between commits, commit and working tree, etc
   grep      Print lines matching a pattern
   log       Show commit logs
   show      Show various types of objects
   status    Show the working tree status
````
or perhaps otherwise clearly marked where command ends

* `  b2 ls   Using the file naming convention that / separates folder names from their contents, returns` - something went very wrong here, same with `sync`
* missing towncrier changelog msg

2024-05-07 19:59 UTC, olzhasar-reef commented
I changed a lot of docstrings to use imperative verb form in the first line. This form arguably better fits the cli help context: more concise and straight to the point.

2024-05-07 20:30 UTC, mjurbanski-reef approved these changes

2024-05-08 17:17 UTC, mjurbanski-reef approved these changes

2024-05-08 20:30 UTC, merged