Apiverv2
reef-technologies/B2_Command_Line_Tool pull request #81
Opened 2021-07-22 14:27 UTC by mpnowacki-reef

2021-07-27 16:52 UTC, mszumocki-reef requested changes

2021-07-27 16:52 UTC, mszumocki-reef commented on b2/json_encoder.py
> -        elif isinstance(obj, FileVersionInfo):
merge those ifinstance checks to one for cases when you're doing as_dict() anyway?

2021-07-27 16:52 UTC, mszumocki-reef commented on doc/source/conf.py
> +        with open(main_help_path, 'r') as main_help_file:
Why open the file twice? You could just change the mode to 'rw'

2021-07-27 16:52 UTC, mszumocki-reef commented on test/integration/test_b2_command_line.py
> +    b2_tool.tearDown_envvar_test('B2_ACCOUNT_INFO')
not even try: finally: here?

2021-07-27 16:52 UTC, mszumocki-reef commented on test/unit/test_console_tool.py
> +    def _trim_leading_spaces(self, s):
This whole function looks like it could be replaced with call to textwrap.dedent

2021-07-29 08:26 UTC, mpnowacki-reef commented on doc/source/conf.py
> +        with open(main_help_path, 'r') as main_help_file:
opening the file with `w+` changes it modification time which causes `nox -s doc` to rebuild the docs and fall into an endless loop

2021-07-29 08:29 UTC, mszumocki-reef commented on doc/source/conf.py
> +        with open(main_help_path, 'r') as main_help_file:
w+ always truncates the file. r+ is what you need

2021-07-29 08:40 UTC, mpnowacki-reef commented on doc/source/conf.py
> +        with open(main_help_path, 'r') as main_help_file:
`r+` doesn't work if the file does not exist

2021-07-29 09:33 UTC, mszumocki-reef approved these changes

2021-07-29 09:34 UTC, mszumocki-reef approved these changes

2021-08-06 01:10 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +        if '' != actual_stderr:
Should be variable vs hardcoded string. Other way not. Weird it sounds. Yoda like.

2021-08-06 01:10 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +        account auth token
```suggestion
        Prepare for a test by authorizing an account and getting an account auth token
```

2021-08-06 14:49 UTC, mpnowacki-reef commented on test/integration/test_b2_command_line.py
> +             p('encrypted')]
right

2021-08-06 14:54 UTC, mpnowacki-reef commented on test/integration/test_b2_command_line.py
> +             p('encrypted')]
done https://github.com/Backblaze/B2_Command_Line_Tool/issues/733

2021-08-06 16:21 UTC, ppolewicz commented on CHANGELOG.md
> +* Log configuration: stack traces are not printed in case of errors byt default, `--verbose` changes that
s/byt/by/

2021-08-06 16:21 UTC, ppolewicz commented on CHANGELOG.md
> +* Log configuration arguments bahaviour altered: `--verbose` and `--debugLogs` can be used at the some time
s/some/same/

2021-08-06 16:21 UTC, ppolewicz commented on CHANGELOG.md
> +* Support of `--metadataDirective` argument in `copy-file-by-id`
+ `(it's detected automatically)`

2021-08-06 16:21 UTC, ppolewicz commented on b2/console_tool.py
> +        self._print('Download finished')
this should be added to changelog

2021-08-06 16:21 UTC, ppolewicz commented on b2/console_tool.py
> +            logger.setLevel(logging.DEBUG)
you've already set this to debug in line 2354

2021-08-06 22:28 UTC, merged