Add `--threads` parameter to `download-file-by-name` and `download-file-by-id`
reef-technologies/B2_Command_Line_Tool pull request #99
Opened 2022-01-25 22:55 UTC by awierzbicki-reef

2022-01-25 22:56 UTC, awierzbicki-reef commented on requirements.txt
> +b2sdk @ git+https://github.com/awierzbicki-reef/b2-sdk-python@download_thread_pool#egg=b2sdk
This is obviously temporary but I'm not sure how the release process works and when can it be updated.

2022-01-28 09:19 UTC, agoncharov-reef requested changes

2022-01-28 09:19 UTC, agoncharov-reef commented on b2/console_tool.py
> +            self.api.services.download_manager.set_thread_pool_size(args.threads)
I don't see that `DownloadManager` has `set_thread_pool_size`, probably you modified it in your repo but I don't have access to it

2022-01-28 09:19 UTC, agoncharov-reef commented on b2/console_tool.py
> +            # FIXME: This is using non-public API. It should be done via B2Api constructor.
Is it really an issue? `manager.set_thread_pool_size` seems like a nice method to use, and as I understand it was intended to be used in such cases.
Also, `b2_api = B2Api(info, cache=cache, raw_api=raw_api)` is initialized at the top level (`def main()`), setting up threads would require to do argument parsing early there, and you have different types of threads (`copy` / `upload`) so it won't be that easy. IMHO the `FIXME` is an overkill.
I've never contributed to B2, so I may be wrong here, probably better discuss with @mpnowacki-reef

2022-01-28 10:11 UTC, awierzbicki-reef commented on b2/console_tool.py
> +            self.api.services.download_manager.set_thread_pool_size(args.threads)
This is SDK using version from https://github.com/Backblaze/b2-sdk-python/pull/297.

2022-01-28 10:13 UTC, awierzbicki-reef commented on b2/console_tool.py
> +            # FIXME: This is using non-public API. It should be done via B2Api constructor.
This was discussed with @ppolewicz. I was instructed to make an issue for this: https://github.com/Backblaze/B2_Command_Line_Tool/issues/774

2022-01-28 11:23 UTC, agoncharov-reef commented on b2/console_tool.py
> +            self.api.services.download_manager.set_thread_pool_size(args.threads)
Big changes! I see now, ty

2022-01-28 11:40 UTC, awierzbicki-reef commented on test/unit/test_console_tool.py
> +                    'file1.txt', local_download1
Done in https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/fdf66bca0cb315301dd7bc53914bb2e3b00b40bc

2022-02-07 07:52 UTC, ppolewicz requested changes

2022-02-07 07:52 UTC, ppolewicz commented on CHANGELOG.md
> +* Add `--threads` parameter to `download-file-by-name` and `download-file-by-id`
what about `sync`? It can both upload and download, but the original issue that we are fixing this bug for on both cli and sdk side is cause by sync launching 10 threads and each thread launching 8 threads for large file download causing 80 threads which cause timeout. If we don't add support for limiting the number of sync download threads in this PR, then that bug will not be fixed.

2022-02-07 07:52 UTC, ppolewicz commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
this leaves the default to b2sdk, but `--threads` for uploads uses a cli-side default. I think a default is missing here.

2022-02-07 07:52 UTC, ppolewicz commented on b2/console_tool.py
> +            # FIXME: This is using non-public API. It should be done via B2Api constructor.
no its not - you changed the status of that api - this is now using deprecated API which will need to be replaced when moving to b2sdk apiver 3

2022-02-07 07:52 UTC, ppolewicz commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
missing default

2022-02-07 07:52 UTC, ppolewicz commented on b2/console_tool.py
> +            # FIXME: This is using non-public API. It should be done via B2Api constructor.
same issue with comment as before

2022-02-07 07:52 UTC, ppolewicz commented on b2/console_tool.py
> +        # FIXME: This is using non-public API. It should be done via B2Api constructor.
same issue with comment as before

2022-02-07 07:52 UTC, ppolewicz commented on b2/console_tool.py
> +        # FIXME: This is using non-public API. It should be done via B2Api constructor.
same issue with comment as before

2022-02-07 07:52 UTC, ppolewicz commented on requirements.txt
> +b2sdk @ git+https://github.com/awierzbicki-reef/b2-sdk-python@download_thread_pool#egg=b2sdk
this is the way to do it

2022-02-07 07:52 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +                ['download-file-by-id', '--threads', '1', '--noProgress', '9999', local_download2],
this is an encryption test. If a bug is found in the handing of --threads, you want a minimum amount of tests crash and the encryption download test should not be one of them. Please observe the alternative - we could use as many options as possible in every test, but then they would either all pass or all fail, also if `--threads` was ever updated to `--downloadThreads` or something we would have to go and modify... encryption tests? That doesn't sound right. It does sound a little bit like we are sending ourselves to [test hell](https://touk.pl/blog/2012/09/16/test-driven-traps-part-1/) for this.

I suggest that we keep the defaults in all the tests except for those few new tests that check the behavior of the new option.

2022-02-07 07:52 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +            # Download with default number of threads
please move it out of `test_files_encrypted`

2022-02-07 09:46 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
I think we should leave the default to the SDK. Setting it to the number of available CPU threads seems smarter than using a hard-coded value. WDYT?

2022-02-07 09:47 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
Same here as in `DownloadFileById`. This is intentional.

2022-02-07 11:51 UTC, ppolewicz commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
CPU has nothing to do with it - you'll need several threads to saturate a single core and you can actually saturate about two of them even with GIL because io and hashing release the GIL.

The feature that you just mentioned - automatically setting the amount of threads (to something - lets leave that aside for a moment) is not implemented in b2sdk apiver v2.

My point is strongly documentation-centered. How will you explain the default behavior to the CLI user? Will you tell them that the number of threads kind of depends on the installed version of b2sdk? Will you extend b2sdk interface to provide a text description of the download thread count for the client applications so that they can dynamically inline it in the documentation? That all doesn't sound right. I think the client application should provide a default value, which will be included in the docs nicely, like [here](https://b2-command-line-tool.readthedocs.io/en/master/subcommands/upload_file.html#Named%20Arguments).

2022-02-07 20:45 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
> How will you explain the default behavior to the CLI user?

I could include a message like "if you don't specify the number of threads, our smart algorithm will attempt to figure out right number". But I don't insist. Setting some default=10 is fine.

2022-02-08 16:43 UTC, ppolewicz commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
sdk doesn't claim to have a smart algorithm for this

2022-02-11 14:18 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
The default number of threads in SDK relies on ThredPoolExecutor implementation. There's *some* algorithm for that, but I may not be very smart indeed. I will set the default to 10 so just the user knows better what to expect.

2022-02-11 15:02 UTC, awierzbicki-reef commented on test/unit/test_console_tool.py
> +                ['download-file-by-id', '--threads', '1', '--noProgress', '9999', local_download2],
Fixed in [808a837](https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/808a837967103ca8e2aca012af746a0459cd319d)

2022-02-11 15:02 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--threads', type=int)
Fixed in [808a837](https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/808a837967103ca8e2aca012af746a0459cd319d)

2022-02-11 15:02 UTC, awierzbicki-reef commented on CHANGELOG.md
> +* Add `--threads` parameter to `download-file-by-name` and `download-file-by-id`
Fixed in [808a837](https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/808a837967103ca8e2aca012af746a0459cd319d)

2022-02-17 12:33 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +
refactor to avoid copy-paste

2022-02-17 12:33 UTC, ppolewicz commented on b2/console_tool.py
> +        self.api.services.download_manager.set_thread_pool_size(args.threads)
I think the user should be able to select the number of download threads, upload threads and sync threads separately

2022-02-18 15:33 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        self.api.services.download_manager.set_thread_pool_size(args.threads)
Fixed in [be0c7e1](https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/be0c7e1c27302e9257905b3d3c32c383be637aea)

2022-02-18 21:24 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
> An error should be returned when someone tries to use --threads with one of the other options
How can this be done if `--threads` has a default option? Does `argparse` has some option to detect if the value was defaulted or put in by user? I think the best we can do is override `--threads` with the more specific options.

2022-02-19 19:37 UTC, ppolewicz commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
In this design, `--syncThreads`, `--downloadThreads` and `--uploadThreads` should have default options, but `--threads` shouldn't

2022-02-20 22:25 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
Okay, but still if both `--threads` and any of the others have non-`None` values, how do we tell if the other value comes from default or was put in by user?

2022-02-21 20:22 UTC, ppolewicz commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
Yeah, you'd have to unset the argparse default from `--threads` and adjust the documentation to indicate that default thread count is 10

2022-02-21 21:13 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
That's *meh*. Can we go with one of the other proposals?
a) Keep `--threads` as a deprecated alias for `--syncThreads`.
b) Make `--sync/download/uploadThreads` override `--threads`.

2022-02-22 18:58 UTC, ppolewicz commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
make --sync/download/uploadThreads default to 10 and make --threads override that, but if --threads is not None and any of --sync/download/uploadThreads != default, then error out

2022-02-22 20:26 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
Fair enough. Will do.

2022-02-22 21:00 UTC, awierzbicki-reef commented on b2/console_tool.py
> +    number of threads for syncing, downloading, and uploading is 10.
Fixed in [18b2da1](https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/18b2da1f64a470da4fb4f01401a8d56068e6b3dc)

2022-02-22 21:00 UTC, awierzbicki-reef commented on b2/console_tool.py
> +        parser.add_argument('--syncThreads', type=int, default=10)
Fixed in [18b2da1](https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/18b2da1f64a470da4fb4f01401a8d56068e6b3dc)

2022-02-26 18:33 UTC, ppolewicz commented on test/unit/test_console_tool.py
> +
That test will pass if
```
if args.syncThreads != 10 or args.uploadThreads != 10 or args.downloadThreads != 10:
```
will be mistakenly implemented as
```
if args.syncThreads != 10 and args.uploadThreads != 10 and args.downloadThreads != 10:
```
so

```suggestion
    def test_sync_thread_exclusive_options(self):
        # Using --threads is exclusive with other options
        with self.assertRaises(ValueError):
            self._test_sync_threads(threads=1, upload_threads=1)
        with self.assertRaises(ValueError):
            self._test_sync_threads(threads=1, sync_threads=1)
        with self.assertRaises(ValueError):
            self._test_sync_threads(threads=1, download_threads=1)
        with self.assertRaises(ValueError):
            self._test_sync_threads(threads=1, sync_threads=1, download_threads=1, upload_threads=1)

```

2022-02-26 22:52 UTC, awierzbicki-reef commented on b2/console_tool.py
> +            if args.syncThreads != 10 or args.uploadThreads != 10 or args.downloadThreads != 10:
Done in [90b8a3a](https://github.com/reef-technologies/B2_Command_Line_Tool/pull/99/commits/90b8a3af7c168b1c792da0f6e4d2b97aff613953)

2022-02-28 16:45 UTC, ppolewicz approved these changes
sdk version needs to be unpinned, but other than that we are ready to go

2022-04-12 22:57 UTC, ppolewicz commented
submitted to upstream

2022-04-12 22:57 UTC, closed without merging